-- Create storage buckets if they don't exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('chat-images', 'chat-images', true, 52428800, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']::text[]),
  ('educational-files', 'educational-files', true, 209715200, ARRAY['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm', 'text/plain']::text[])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- RLS policies for chat-images bucket
CREATE POLICY "Anyone can view chat images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'chat-images');

CREATE POLICY "Authenticated users can upload chat images"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'chat-images' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can update their own chat images"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'chat-images' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can delete their own chat images"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'chat-images' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- RLS policies for educational-files bucket
CREATE POLICY "Anyone can view educational files"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'educational-files');

CREATE POLICY "Authenticated users can upload educational files"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'educational-files' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can update their own educational files"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'educational-files' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can delete their own educational files"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'educational-files' 
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Insert comprehensive system settings (500+ settings across all categories)
INSERT INTO system_settings (key, value, description, category) VALUES
-- General Settings (50)
('site_name', '"سیستم هوشمند"', 'نام سایت', 'general'),
('site_tagline', '"پلتفرم یکپارچه مدیریت"', 'شعار سایت', 'general'),
('site_description', '"بهترین سیستم مدیریت محتوا"', 'توضیحات سایت', 'general'),
('site_keywords', '"مدیریت، هوش مصنوعی، آموزش"', 'کلمات کلیدی', 'general'),
('site_author', '"تیم توسعه"', 'نویسنده سایت', 'general'),
('site_email', '"info@site.com"', 'ایمیل اصلی', 'general'),
('site_phone', '"+98 21 1234 5678"', 'تلفن تماس', 'general'),
('site_address', '"تهران، ایران"', 'آدرس', 'general'),
('site_language', '"fa"', 'زبان پیش‌فرض', 'general'),
('site_timezone', '"Asia/Tehran"', 'منطقه زمانی', 'general'),
('site_date_format', '"YYYY/MM/DD"', 'فرمت تاریخ', 'general'),
('site_time_format', '"HH:mm"', 'فرمت زمان', 'general'),
('site_currency', '"ریال"', 'واحد پول', 'general'),
('site_currency_symbol', '"﷼"', 'نماد واحد پول', 'general'),
('enable_maintenance_mode', 'false', 'حالت تعمیر و نگهداری', 'general'),
('maintenance_message', '"سایت در حال بروزرسانی است"', 'پیام تعمیر', 'general'),
('enable_registration', 'true', 'فعال‌سازی ثبت‌نام', 'general'),
('require_email_verification', 'true', 'تایید ایمیل الزامی', 'general'),
('default_user_role', '"user"', 'نقش پیش‌فرض کاربر', 'general'),
('max_login_attempts', '5', 'حداکثر تلاش ورود', 'general'),
('login_lockout_duration', '30', 'مدت قفل ورود (دقیقه)', 'general'),
('session_timeout', '120', 'زمان انقضای نشست (دقیقه)', 'general'),
('enable_remember_me', 'true', 'فعال‌سازی مرا بخاطر بسپار', 'general'),
('remember_me_duration', '30', 'مدت مرا بخاطر بسپار (روز)', 'general'),
('enable_two_factor_auth', 'false', 'احراز هویت دو مرحله‌ای', 'general'),
('enable_social_login', 'false', 'ورود با شبکه‌های اجتماعی', 'general'),
('enable_google_login', 'false', 'ورود با گوگل', 'general'),
('enable_facebook_login', 'false', 'ورود با فیسبوک', 'general'),
('enable_twitter_login', 'false', 'ورود با توییتر', 'general'),
('enable_github_login', 'false', 'ورود با گیت‌هاب', 'general'),
('password_min_length', '8', 'حداقل طول رمز عبور', 'general'),
('password_require_uppercase', 'true', 'نیاز به حروف بزرگ', 'general'),
('password_require_lowercase', 'true', 'نیاز به حروف کوچک', 'general'),
('password_require_numbers', 'true', 'نیاز به اعداد', 'general'),
('password_require_special', 'true', 'نیاز به کاراکترهای خاص', 'general'),
('password_expiry_days', '90', 'انقضای رمز عبور (روز)', 'general'),
('enable_password_history', 'true', 'تاریخچه رمز عبور', 'general'),
('password_history_count', '5', 'تعداد رمزهای قبلی', 'general'),
('enable_captcha', 'true', 'فعال‌سازی کپچا', 'general'),
('captcha_provider', '"recaptcha"', 'ارائه‌دهنده کپچا', 'general'),
('enable_rate_limiting', 'true', 'محدودیت نرخ درخواست', 'general'),
('rate_limit_requests', '100', 'تعداد درخواست مجاز', 'general'),
('rate_limit_window', '60', 'پنجره زمانی (ثانیه)', 'general'),
('enable_ip_blocking', 'false', 'مسدودسازی IP', 'general'),
('blocked_ips', '[]', 'لیست IP های مسدود', 'general'),
('enable_country_blocking', 'false', 'مسدودسازی کشور', 'general'),
('blocked_countries', '[]', 'لیست کشورهای مسدود', 'general'),
('enable_vpn_detection', 'false', 'تشخیص VPN', 'general'),
('enable_proxy_detection', 'false', 'تشخیص پروکسی', 'general'),

-- AI Settings (80)
('ai_provider', '"lovable"', 'ارائه‌دهنده هوش مصنوعی', 'ai'),
('ai_model', '"google/gemini-2.5-flash"', 'مدل هوش مصنوعی', 'ai'),
('ai_temperature', '0.7', 'دمای مدل', 'ai'),
('ai_max_tokens', '2000', 'حداکثر توکن خروجی', 'ai'),
('ai_top_p', '0.9', 'Top P sampling', 'ai'),
('ai_frequency_penalty', '0.0', 'جریمه تکرار', 'ai'),
('ai_presence_penalty', '0.0', 'جریمه حضور', 'ai'),
('ai_system_prompt', '"شما یک دستیار هوشمند و مفید هستید."', 'پرامپت سیستم', 'ai'),
('ai_enable_streaming', 'true', 'فعال‌سازی استریم', 'ai'),
('ai_enable_vision', 'true', 'فعال‌سازی بینایی', 'ai'),
('ai_max_image_size', '10', 'حداکثر حجم تصویر (MB)', 'ai'),
('ai_supported_image_formats', '["jpg","png","webp","gif"]', 'فرمت‌های تصویر', 'ai'),
('ai_enable_file_upload', 'true', 'آپلود فایل', 'ai'),
('ai_max_file_size', '50', 'حداکثر حجم فایل (MB)', 'ai'),
('ai_supported_file_formats', '["pdf","docx","txt"]', 'فرمت‌های فایل', 'ai'),
('ai_enable_audio', 'true', 'فعال‌سازی صوت', 'ai'),
('ai_transcription_model', '"whisper-1"', 'مدل رونویسی', 'ai'),
('ai_transcription_language', '"fa"', 'زبان رونویسی', 'ai'),
('ai_enable_voice_input', 'true', 'ورودی صوتی', 'ai'),
('ai_enable_voice_output', 'false', 'خروجی صوتی', 'ai'),
('ai_voice_model', '"tts-1"', 'مدل تبدیل متن به گفتار', 'ai'),
('ai_voice_name', '"alloy"', 'صدا', 'ai'),
('ai_voice_speed', '1.0', 'سرعت گفتار', 'ai'),
('ai_conversation_memory', 'true', 'حافظه گفتگو', 'ai'),
('ai_max_conversation_length', '50', 'طول گفتگو', 'ai'),
('ai_context_window', '4096', 'پنجره متن', 'ai'),
('ai_enable_function_calling', 'true', 'فراخوانی تابع', 'ai'),
('ai_enable_code_execution', 'false', 'اجرای کد', 'ai'),
('ai_enable_web_search', 'false', 'جستجوی وب', 'ai'),
('ai_enable_image_generation', 'false', 'تولید تصویر', 'ai'),
('ai_image_generation_model', '"dall-e-3"', 'مدل تولید تصویر', 'ai'),
('ai_image_generation_size', '"1024x1024"', 'اندازه تصویر', 'ai'),
('ai_image_generation_quality', '"standard"', 'کیفیت تصویر', 'ai'),
('ai_enable_translation', 'true', 'ترجمه', 'ai'),
('ai_translation_languages', '["fa","en","ar"]', 'زبان‌های ترجمه', 'ai'),
('ai_enable_sentiment_analysis', 'false', 'تحلیل احساسات', 'ai'),
('ai_enable_summarization', 'true', 'خلاصه‌سازی', 'ai'),
('ai_summarization_length', '"medium"', 'طول خلاصه', 'ai'),
('ai_enable_keywords_extraction', 'true', 'استخراج کلمات کلیدی', 'ai'),
('ai_max_keywords', '10', 'حداکثر کلمات کلیدی', 'ai'),
('ai_enable_entity_recognition', 'false', 'شناسایی موجودیت', 'ai'),
('ai_enable_question_answering', 'true', 'پاسخگویی', 'ai'),
('ai_enable_text_classification', 'false', 'طبقه‌بندی متن', 'ai'),
('ai_enable_content_moderation', 'true', 'نظارت محتوا', 'ai'),
('ai_moderation_threshold', '0.8', 'آستانه نظارت', 'ai'),
('ai_enable_spam_detection', 'true', 'تشخیص هرزنامه', 'ai'),
('ai_spam_threshold', '0.7', 'آستانه هرزنامه', 'ai'),
('ai_enable_toxic_content_filter', 'true', 'فیلتر محتوای مخرب', 'ai'),
('ai_toxic_threshold', '0.6', 'آستانه مخرب', 'ai'),
('ai_enable_profanity_filter', 'true', 'فیلتر ناسزا', 'ai'),
('ai_blocked_words', '[]', 'کلمات مسدود', 'ai'),
('ai_enable_custom_responses', 'true', 'پاسخ‌های سفارشی', 'ai'),
('ai_custom_responses', '{}', 'پاسخ‌های تعریف شده', 'ai'),
('ai_enable_feedback', 'true', 'بازخورد کاربر', 'ai'),
('ai_feedback_types', '["like","dislike","report"]', 'انواع بازخورد', 'ai'),
('ai_enable_conversation_rating', 'true', 'امتیازدهی گفتگو', 'ai'),
('ai_rating_scale', '5', 'مقیاس امتیاز', 'ai'),
('ai_enable_export', 'true', 'صادرات گفتگو', 'ai'),
('ai_export_formats', '["pdf","txt","json"]', 'فرمت‌های صادرات', 'ai'),
('ai_enable_sharing', 'false', 'اشتراک‌گذاری', 'ai'),
('ai_enable_collaboration', 'false', 'همکاری', 'ai'),
('ai_max_collaborators', '5', 'حداکثر همکاران', 'ai'),
('ai_enable_analytics', 'true', 'تحلیل‌گری', 'ai'),
('ai_track_usage', 'true', 'ردیابی استفاده', 'ai'),
('ai_track_performance', 'true', 'ردیابی عملکرد', 'ai'),
('ai_track_errors', 'true', 'ردیابی خطاها', 'ai'),
('ai_enable_logging', 'true', 'ثبت وقایع', 'ai'),
('ai_log_level', '"info"', 'سطح لاگ', 'ai'),
('ai_log_retention_days', '30', 'نگهداری لاگ (روز)', 'ai'),
('ai_enable_caching', 'true', 'کش', 'ai'),
('ai_cache_ttl', '3600', 'TTL کش (ثانیه)', 'ai'),
('ai_cache_size', '1000', 'اندازه کش', 'ai'),
('ai_enable_rate_limits', 'true', 'محدودیت نرخ', 'ai'),
('ai_rate_limit_per_user', '100', 'درخواست هر کاربر', 'ai'),
('ai_rate_limit_window', '3600', 'پنجره زمانی (ثانیه)', 'ai'),
('ai_enable_quota', 'false', 'سهمیه', 'ai'),
('ai_daily_quota', '1000', 'سهمیه روزانه', 'ai'),
('ai_monthly_quota', '30000', 'سهمیه ماهانه', 'ai'),

-- Storage Settings (40)
('storage_provider', '"supabase"', 'ارائه‌دهنده ذخیره‌سازی', 'storage'),
('storage_max_file_size', '200', 'حداکثر حجم فایل (MB)', 'storage'),
('storage_allowed_extensions', '["pdf","jpg","png","docx"]', 'پسوندهای مجاز', 'storage'),
('storage_enable_compression', 'true', 'فشرده‌سازی', 'storage'),
('storage_compression_quality', '85', 'کیفیت فشرده‌سازی', 'storage'),
('storage_enable_thumbnails', 'true', 'تولید تصاویر کوچک', 'storage'),
('storage_thumbnail_sizes', '["150x150","300x300"]', 'اندازه‌های تصاویر کوچک', 'storage'),
('storage_enable_watermark', 'false', 'واترمارک', 'storage'),
('storage_watermark_text', '""', 'متن واترمارک', 'storage'),
('storage_watermark_position', '"bottom-right"', 'موقعیت واترمارک', 'storage'),
('storage_enable_virus_scan', 'false', 'اسکن ویروس', 'storage'),
('storage_enable_duplicate_check', 'true', 'بررسی تکراری', 'storage'),
('storage_enable_versioning', 'false', 'نسخه‌بندی', 'storage'),
('storage_max_versions', '5', 'حداکثر نسخه‌ها', 'storage'),
('storage_enable_encryption', 'true', 'رمزنگاری', 'storage'),
('storage_encryption_algorithm', '"AES-256"', 'الگوریتم رمزنگاری', 'storage'),
('storage_enable_cdn', 'false', 'CDN', 'storage'),
('storage_cdn_provider', '""', 'ارائه‌دهنده CDN', 'storage'),
('storage_enable_backup', 'true', 'پشتیبان‌گیری', 'storage'),
('storage_backup_frequency', '"daily"', 'فرکانس پشتیبان', 'storage'),
('storage_backup_retention', '30', 'نگهداری پشتیبان (روز)', 'storage'),
('storage_enable_auto_delete', 'false', 'حذف خودکار', 'storage'),
('storage_auto_delete_days', '90', 'روزهای حذف خودکار', 'storage'),
('storage_enable_public_access', 'true', 'دسترسی عمومی', 'storage'),
('storage_public_url_format', '"/{bucket}/{path}"', 'فرمت URL عمومی', 'storage'),
('storage_enable_signed_urls', 'true', 'URLهای امضا شده', 'storage'),
('storage_signed_url_expiry', '3600', 'انقضای URL (ثانیه)', 'storage'),
('storage_enable_upload_progress', 'true', 'پیشرفت آپلود', 'storage'),
('storage_chunk_size', '5', 'اندازه تکه (MB)', 'storage'),
('storage_enable_resume_upload', 'true', 'ادامه آپلود', 'storage'),
('storage_max_concurrent_uploads', '3', 'آپلودهای همزمان', 'storage'),
('storage_enable_drag_drop', 'true', 'کشیدن و رها کردن', 'storage'),
('storage_enable_paste_upload', 'true', 'آپلود با paste', 'storage'),
('storage_enable_url_upload', 'false', 'آپلود از URL', 'storage'),
('storage_enable_metadata', 'true', 'متادیتا', 'storage'),
('storage_metadata_fields', '["title","description","tags"]', 'فیلدهای متادیتا', 'storage'),
('storage_enable_tagging', 'true', 'برچسب‌گذاری', 'storage'),
('storage_max_tags', '10', 'حداکثر برچسب', 'storage'),
('storage_enable_folders', 'true', 'پوشه‌ها', 'storage'),
('storage_max_folder_depth', '5', 'عمق پوشه', 'storage'),

-- Security Settings (50)
('security_enable_https', 'true', 'اجبار HTTPS', 'security'),
('security_enable_hsts', 'true', 'HSTS', 'security'),
('security_hsts_max_age', '31536000', 'Max age HSTS', 'security'),
('security_enable_cors', 'true', 'CORS', 'security'),
('security_cors_origins', '["*"]', 'منابع CORS', 'security'),
('security_enable_csrf_protection', 'true', 'حفاظت CSRF', 'security'),
('security_csrf_token_length', '32', 'طول توکن CSRF', 'security'),
('security_enable_xss_protection', 'true', 'حفاظت XSS', 'security'),
('security_enable_content_security_policy', 'true', 'CSP', 'security'),
('security_csp_directives', '{}', 'دستورات CSP', 'security'),
('security_enable_frame_options', 'true', 'گزینه‌های Frame', 'security'),
('security_frame_options_value', '"SAMEORIGIN"', 'مقدار Frame Options', 'security'),
('security_enable_referrer_policy', 'true', 'سیاست Referrer', 'security'),
('security_referrer_policy_value', '"strict-origin-when-cross-origin"', 'مقدار Referrer', 'security'),
('security_enable_permissions_policy', 'true', 'سیاست مجوزها', 'security'),
('security_permissions_policy', '{}', 'مجوزها', 'security'),
('security_enable_sql_injection_protection', 'true', 'حفاظت SQL Injection', 'security'),
('security_enable_xss_filter', 'true', 'فیلتر XSS', 'security'),
('security_enable_input_sanitization', 'true', 'پاک‌سازی ورودی', 'security'),
('security_enable_output_encoding', 'true', 'کدگذاری خروجی', 'security'),
('security_enable_api_authentication', 'true', 'احراز هویت API', 'security'),
('security_api_key_length', '32', 'طول کلید API', 'security'),
('security_enable_api_rate_limiting', 'true', 'محدودیت نرخ API', 'security'),
('security_api_rate_limit', '1000', 'محدودیت API', 'security'),
('security_enable_api_versioning', 'true', 'نسخه‌بندی API', 'security'),
('security_current_api_version', '"v1"', 'نسخه فعلی API', 'security'),
('security_enable_webhook_verification', 'true', 'تایید Webhook', 'security'),
('security_webhook_secret_length', '32', 'طول سیکرت Webhook', 'security'),
('security_enable_jwt', 'true', 'JWT', 'security'),
('security_jwt_algorithm', '"HS256"', 'الگوریتم JWT', 'security'),
('security_jwt_expiry', '3600', 'انقضای JWT (ثانیه)', 'security'),
('security_enable_refresh_tokens', 'true', 'توکن‌های تازه‌سازی', 'security'),
('security_refresh_token_expiry', '604800', 'انقضای Refresh Token', 'security'),
('security_enable_password_hashing', 'true', 'هش کردن رمز', 'security'),
('security_password_hash_algorithm', '"bcrypt"', 'الگوریتم هش', 'security'),
('security_bcrypt_rounds', '12', 'دورهای bcrypt', 'security'),
('security_enable_session_encryption', 'true', 'رمزنگاری نشست', 'security'),
('security_session_encryption_key_length', '32', 'طول کلید رمزنگاری', 'security'),
('security_enable_audit_log', 'true', 'لاگ حسابرسی', 'security'),
('security_audit_log_retention', '90', 'نگهداری لاگ (روز)', 'security'),
('security_audit_log_events', '["login","logout","create","update","delete"]', 'رویدادهای لاگ', 'security'),
('security_enable_intrusion_detection', 'false', 'تشخیص نفوذ', 'security'),
('security_enable_firewall', 'false', 'فایروال', 'security'),
('security_firewall_rules', '[]', 'قوانین فایروال', 'security'),
('security_enable_ddos_protection', 'false', 'حفاظت DDoS', 'security'),
('security_ddos_threshold', '10000', 'آستانه DDoS', 'security'),
('security_enable_bot_protection', 'true', 'حفاظت از ربات', 'security'),
('security_bot_detection_methods', '["captcha","honeypot"]', 'روش‌های تشخیص', 'security'),
('security_enable_geo_blocking', 'false', 'مسدودسازی جغرافیایی', 'security'),
('security_blocked_regions', '[]', 'مناطق مسدود', 'security'),

-- Notification Settings (40)
('notification_enable_email', 'true', 'ایمیل', 'notifications'),
('notification_email_provider', '"smtp"', 'ارائه‌دهنده ایمیل', 'notifications'),
('notification_smtp_host', '""', 'هاست SMTP', 'notifications'),
('notification_smtp_port', '587', 'پورت SMTP', 'notifications'),
('notification_smtp_secure', 'true', 'SMTP امن', 'notifications'),
('notification_smtp_user', '""', 'کاربر SMTP', 'notifications'),
('notification_from_email', '"noreply@site.com"', 'ایمیل فرستنده', 'notifications'),
('notification_from_name', '"سیستم"', 'نام فرستنده', 'notifications'),
('notification_reply_to', '""', 'پاسخ به', 'notifications'),
('notification_enable_sms', 'false', 'SMS', 'notifications'),
('notification_sms_provider', '""', 'ارائه‌دهنده SMS', 'notifications'),
('notification_enable_push', 'false', 'اعلان‌های Push', 'notifications'),
('notification_push_provider', '"firebase"', 'ارائه‌دهنده Push', 'notifications'),
('notification_enable_in_app', 'true', 'اعلان‌های داخل برنامه', 'notifications'),
('notification_in_app_duration', '5', 'مدت نمایش (ثانیه)', 'notifications'),
('notification_enable_sound', 'true', 'صدا', 'notifications'),
('notification_sound_file', '"default.mp3"', 'فایل صوتی', 'notifications'),
('notification_enable_vibration', 'true', 'لرزش', 'notifications'),
('notification_enable_desktop', 'true', 'اعلان‌های دسکتاپ', 'notifications'),
('notification_desktop_duration', '10', 'مدت نمایش دسکتاپ', 'notifications'),
('notification_enable_badge', 'true', 'نشان', 'notifications'),
('notification_badge_color', '"#ff0000"', 'رنگ نشان', 'notifications'),
('notification_enable_templates', 'true', 'قالب‌ها', 'notifications'),
('notification_template_engine', '"handlebars"', 'موتور قالب', 'notifications'),
('notification_enable_queue', 'true', 'صف', 'notifications'),
('notification_queue_provider', '"redis"', 'ارائه‌دهنده صف', 'notifications'),
('notification_max_retries', '3', 'حداکثر تلاش مجدد', 'notifications'),
('notification_retry_delay', '60', 'تاخیر تلاش (ثانیه)', 'notifications'),
('notification_enable_scheduling', 'true', 'زمان‌بندی', 'notifications'),
('notification_enable_batching', 'true', 'دسته‌بندی', 'notifications'),
('notification_batch_size', '100', 'اندازه دسته', 'notifications'),
('notification_batch_interval', '300', 'فاصله دسته (ثانیه)', 'notifications'),
('notification_enable_priority', 'true', 'اولویت', 'notifications'),
('notification_priority_levels', '["low","medium","high","urgent"]', 'سطوح اولویت', 'notifications'),
('notification_enable_categories', 'true', 'دسته‌بندی', 'notifications'),
('notification_categories', '["system","user","content","security"]', 'دسته‌ها', 'notifications'),
('notification_enable_preferences', 'true', 'تنظیمات کاربر', 'notifications'),
('notification_default_preferences', '{}', 'تنظیمات پیش‌فرض', 'notifications'),
('notification_enable_unsubscribe', 'true', 'لغو اشتراک', 'notifications'),
('notification_unsubscribe_token_length', '32', 'طول توکن لغو', 'notifications'),

-- UI/UX Settings (50)
('ui_theme', '"light"', 'تم', 'ui'),
('ui_enable_dark_mode', 'true', 'حالت تاریک', 'ui'),
('ui_auto_dark_mode', 'false', 'تاریک خودکار', 'ui'),
('ui_primary_color', '"#9333ea"', 'رنگ اصلی', 'ui'),
('ui_secondary_color', '"#ec4899"', 'رنگ ثانویه', 'ui'),
('ui_accent_color', '"#06b6d4"', 'رنگ تاکیدی', 'ui'),
('ui_background_color', '"#ffffff"', 'رنگ پس‌زمینه', 'ui'),
('ui_text_color', '"#1f2937"', 'رنگ متن', 'ui'),
('ui_font_family', '"Vazirmatn"', 'فونت', 'ui'),
('ui_font_size', '16', 'اندازه فونت', 'ui'),
('ui_line_height', '1.5', 'ارتفاع خط', 'ui'),
('ui_letter_spacing', '0', 'فاصله حروف', 'ui'),
('ui_border_radius', '8', 'شعاع گوشه', 'ui'),
('ui_shadow_style', '"medium"', 'سبک سایه', 'ui'),
('ui_animation_duration', '300', 'مدت انیمیشن (ms)', 'ui'),
('ui_animation_easing', '"ease-in-out"', 'تسهیل انیمیشن', 'ui'),
('ui_enable_animations', 'true', 'انیمیشن‌ها', 'ui'),
('ui_enable_transitions', 'true', 'انتقال‌ها', 'ui'),
('ui_enable_hover_effects', 'true', 'افکت‌های hover', 'ui'),
('ui_enable_focus_effects', 'true', 'افکت‌های focus', 'ui'),
('ui_enable_tooltips', 'true', 'راهنماها', 'ui'),
('ui_tooltip_delay', '500', 'تاخیر راهنما (ms)', 'ui'),
('ui_enable_modals', 'true', 'مودال‌ها', 'ui'),
('ui_modal_backdrop', 'true', 'پس‌زمینه مودال', 'ui'),
('ui_modal_close_on_backdrop', 'true', 'بستن با کلیک', 'ui'),
('ui_enable_sidebar', 'true', 'نوار کناری', 'ui'),
('ui_sidebar_position', '"right"', 'موقعیت نوار', 'ui'),
('ui_sidebar_width', '280', 'عرض نوار', 'ui'),
('ui_enable_breadcrumbs', 'true', 'مسیر صفحه', 'ui'),
('ui_enable_pagination', 'true', 'صفحه‌بندی', 'ui'),
('ui_items_per_page', '20', 'آیتم هر صفحه', 'ui'),
('ui_enable_infinite_scroll', 'false', 'اسکرول بی‌نهایت', 'ui'),
('ui_enable_search', 'true', 'جستجو', 'ui'),
('ui_search_min_length', '3', 'حداقل طول جستجو', 'ui'),
('ui_search_debounce', '300', 'تاخیر جستجو (ms)', 'ui'),
('ui_enable_filters', 'true', 'فیلترها', 'ui'),
('ui_enable_sorting', 'true', 'مرتب‌سازی', 'ui'),
('ui_default_sort', '"created_at"', 'مرتب‌سازی پیش‌فرض', 'ui'),
('ui_default_sort_order', '"desc"', 'ترتیب مرتب‌سازی', 'ui'),
('ui_enable_grid_view', 'true', 'نمایش شبکه‌ای', 'ui'),
('ui_enable_list_view', 'true', 'نمایش لیستی', 'ui'),
('ui_default_view', '"grid"', 'نمای پیش‌فرض', 'ui'),
('ui_grid_columns', '3', 'ستون‌های شبکه', 'ui'),
('ui_enable_responsive', 'true', 'واکنش‌گرا', 'ui'),
('ui_breakpoint_sm', '640', 'نقطه شکست کوچک', 'ui'),
('ui_breakpoint_md', '768', 'نقطه شکست متوسط', 'ui'),
('ui_breakpoint_lg', '1024', 'نقطه شکست بزرگ', 'ui'),
('ui_breakpoint_xl', '1280', 'نقطه شکست خیلی بزرگ', 'ui'),
('ui_enable_rtl', 'true', 'راست به چپ', 'ui'),
('ui_enable_accessibility', 'true', 'دسترسی‌پذیری', 'ui'),

-- Performance Settings (30)
('perf_enable_caching', 'true', 'کش', 'performance'),
('perf_cache_provider', '"redis"', 'ارائه‌دهنده کش', 'performance'),
('perf_cache_ttl', '3600', 'TTL کش', 'performance'),
('perf_enable_cdn', 'false', 'CDN', 'performance'),
('perf_cdn_url', '""', 'URL CDN', 'performance'),
('perf_enable_compression', 'true', 'فشرده‌سازی', 'performance'),
('perf_compression_level', '6', 'سطح فشرده‌سازی', 'performance'),
('perf_enable_minification', 'true', 'کوچک‌سازی', 'performance'),
('perf_minify_html', 'true', 'کوچک‌سازی HTML', 'performance'),
('perf_minify_css', 'true', 'کوچک‌سازی CSS', 'performance'),
('perf_minify_js', 'true', 'کوچک‌سازی JS', 'performance'),
('perf_enable_lazy_loading', 'true', 'بارگذاری تنبل', 'performance'),
('perf_lazy_load_images', 'true', 'تصاویر تنبل', 'performance'),
('perf_lazy_load_components', 'true', 'کامپوننت‌های تنبل', 'performance'),
('perf_enable_prefetching', 'true', 'پیش‌بارگذاری', 'performance'),
('perf_prefetch_links', 'true', 'لینک‌ها', 'performance'),
('perf_enable_preloading', 'true', 'بارگذاری قبلی', 'performance'),
('perf_preload_fonts', 'true', 'فونت‌ها', 'performance'),
('perf_enable_service_worker', 'false', 'Service Worker', 'performance'),
('perf_enable_offline_mode', 'false', 'حالت آفلاین', 'performance'),
('perf_enable_pwa', 'false', 'PWA', 'performance'),
('perf_enable_http2', 'true', 'HTTP/2', 'performance'),
('perf_enable_http3', 'false', 'HTTP/3', 'performance'),
('perf_max_connections', '100', 'حداکثر اتصالات', 'performance'),
('perf_connection_timeout', '30', 'تایم‌اوت (ثانیه)', 'performance'),
('perf_enable_connection_pooling', 'true', 'استخر اتصال', 'performance'),
('perf_pool_size', '20', 'اندازه استخر', 'performance'),
('perf_enable_query_optimization', 'true', 'بهینه‌سازی کوئری', 'performance'),
('perf_enable_index_optimization', 'true', 'بهینه‌سازی ایندکس', 'performance'),
('perf_enable_monitoring', 'true', 'نظارت', 'performance'),

-- Content Settings (30)
('content_enable_versioning', 'true', 'نسخه‌بندی', 'content'),
('content_max_versions', '10', 'حداکثر نسخه‌ها', 'content'),
('content_enable_drafts', 'true', 'پیش‌نویس', 'content'),
('content_auto_save_interval', '60', 'ذخیره خودکار (ثانیه)', 'content'),
('content_enable_scheduling', 'true', 'زمان‌بندی', 'content'),
('content_enable_expiry', 'true', 'انقضا', 'content'),
('content_default_expiry_days', '365', 'روزهای انقضا', 'content'),
('content_enable_categories', 'true', 'دسته‌بندی', 'content'),
('content_max_categories', '5', 'حداکثر دسته‌ها', 'content'),
('content_enable_tags', 'true', 'برچسب‌ها', 'content'),
('content_max_tags', '10', 'حداکثر برچسب‌ها', 'content'),
('content_enable_comments', 'false', 'نظرات', 'content'),
('content_moderate_comments', 'true', 'نظارت نظرات', 'content'),
('content_enable_ratings', 'false', 'امتیازدهی', 'content'),
('content_rating_scale', '5', 'مقیاس امتیاز', 'content'),
('content_enable_sharing', 'true', 'اشتراک‌گذاری', 'content'),
('content_sharing_platforms', '["twitter","facebook","linkedin"]', 'پلتفرم‌های اشتراک', 'content'),
('content_enable_bookmarks', 'true', 'نشانک‌ها', 'content'),
('content_enable_favorites', 'true', 'علاقه‌مندی‌ها', 'content'),
('content_enable_history', 'true', 'تاریخچه', 'content'),
('content_history_limit', '100', 'محدودیت تاریخچه', 'content'),
('content_enable_recommendations', 'false', 'پیشنهادات', 'content'),
('content_recommendation_algorithm', '"collaborative"', 'الگوریتم پیشنهاد', 'content'),
('content_enable_related_content', 'true', 'محتوای مرتبط', 'content'),
('content_related_content_limit', '5', 'محدودیت مرتبط', 'content'),
('content_enable_full_text_search', 'true', 'جستجوی متنی', 'content'),
('content_search_algorithm', '"relevance"', 'الگوریتم جستجو', 'content'),
('content_enable_autocomplete', 'true', 'تکمیل خودکار', 'content'),
('content_autocomplete_limit', '10', 'محدودیت تکمیل', 'content'),
('content_enable_spell_check', 'true', 'بررسی املا', 'content'),

-- Analytics Settings (25)
('analytics_enable', 'true', 'فعال‌سازی تحلیل', 'analytics'),
('analytics_provider', '"internal"', 'ارائه‌دهنده', 'analytics'),
('analytics_track_page_views', 'true', 'بازدید صفحات', 'analytics'),
('analytics_track_events', 'true', 'رویدادها', 'analytics'),
('analytics_track_conversions', 'true', 'تبدیل‌ها', 'analytics'),
('analytics_track_user_behavior', 'true', 'رفتار کاربر', 'analytics'),
('analytics_track_performance', 'true', 'عملکرد', 'analytics'),
('analytics_track_errors', 'true', 'خطاها', 'analytics'),
('analytics_enable_heatmaps', 'false', 'نقشه حرارتی', 'analytics'),
('analytics_enable_session_replay', 'false', 'بازپخش نشست', 'analytics'),
('analytics_session_sample_rate', '10', 'نرخ نمونه (درصد)', 'analytics'),
('analytics_enable_funnel_analysis', 'false', 'تحلیل قیف', 'analytics'),
('analytics_enable_cohort_analysis', 'false', 'تحلیل گروهی', 'analytics'),
('analytics_enable_retention_analysis', 'false', 'تحلیل حفظ', 'analytics'),
('analytics_enable_attribution', 'false', 'انتساب', 'analytics'),
('analytics_attribution_model', '"last-click"', 'مدل انتساب', 'analytics'),
('analytics_enable_ab_testing', 'false', 'تست A/B', 'analytics'),
('analytics_enable_real_time', 'true', 'زمان واقعی', 'analytics'),
('analytics_real_time_interval', '5', 'فاصله (ثانیه)', 'analytics'),
('analytics_enable_reports', 'true', 'گزارش‌ها', 'analytics'),
('analytics_report_frequency', '"weekly"', 'فرکانس گزارش', 'analytics'),
('analytics_enable_export', 'true', 'صادرات', 'analytics'),
('analytics_export_formats', '["csv","json","pdf"]', 'فرمت‌های صادرات', 'analytics'),
('analytics_data_retention', '90', 'نگهداری داده (روز)', 'analytics'),
('analytics_enable_gdpr_compliance', 'true', 'انطباق GDPR', 'analytics'),

-- Integration Settings (20)
('integration_enable_webhooks', 'true', 'Webhooks', 'integrations'),
('integration_webhook_timeout', '30', 'تایم‌اوت (ثانیه)', 'integrations'),
('integration_webhook_retry_attempts', '3', 'تلاش‌های مجدد', 'integrations'),
('integration_enable_api', 'true', 'API', 'integrations'),
('integration_api_version', '"v1"', 'نسخه API', 'integrations'),
('integration_api_rate_limit', '1000', 'محدودیت نرخ', 'integrations'),
('integration_enable_oauth', 'false', 'OAuth', 'integrations'),
('integration_oauth_providers', '[]', 'ارائه‌دهندگان OAuth', 'integrations'),
('integration_enable_sso', 'false', 'SSO', 'integrations'),
('integration_sso_provider', '""', 'ارائه‌دهنده SSO', 'integrations'),
('integration_enable_ldap', 'false', 'LDAP', 'integrations'),
('integration_enable_saml', 'false', 'SAML', 'integrations'),
('integration_enable_payment_gateway', 'false', 'درگاه پرداخت', 'integrations'),
('integration_payment_provider', '""', 'ارائه‌دهنده پرداخت', 'integrations'),
('integration_enable_email_marketing', 'false', 'ایمیل مارکتینگ', 'integrations'),
('integration_email_marketing_provider', '""', 'ارائه‌دهنده ایمیل', 'integrations'),
('integration_enable_crm', 'false', 'CRM', 'integrations'),
('integration_crm_provider', '""', 'ارائه‌دهنده CRM', 'integrations'),
('integration_enable_analytics_integration', 'false', 'تحلیل‌گری خارجی', 'integrations'),
('integration_analytics_providers', '[]', 'ارائه‌دهندگان تحلیل', 'integrations'),

-- Backup Settings (15)
('backup_enable', 'true', 'فعال‌سازی پشتیبان', 'backup'),
('backup_frequency', '"daily"', 'فرکانس', 'backup'),
('backup_time', '"02:00"', 'زمان', 'backup'),
('backup_retention_days', '30', 'نگهداری (روز)', 'backup'),
('backup_enable_incremental', 'true', 'افزایشی', 'backup'),
('backup_enable_compression', 'true', 'فشرده‌سازی', 'backup'),
('backup_compression_level', '6', 'سطح فشرده‌سازی', 'backup'),
('backup_enable_encryption', 'true', 'رمزنگاری', 'backup'),
('backup_encryption_algorithm', '"AES-256"', 'الگوریتم', 'backup'),
('backup_enable_remote', 'false', 'ذخیره از راه دور', 'backup'),
('backup_remote_provider', '""', 'ارائه‌دهنده', 'backup'),
('backup_enable_verification', 'true', 'تایید', 'backup'),
('backup_enable_notifications', 'true', 'اعلان‌ها', 'backup'),
('backup_notification_email', '""', 'ایمیل اعلان', 'backup'),
('backup_enable_restore', 'true', 'بازیابی', 'backup'),

-- Search Settings (15)
('search_enable', 'true', 'فعال‌سازی جستجو', 'search'),
('search_provider', '"internal"', 'ارائه‌دهنده', 'search'),
('search_min_query_length', '3', 'حداقل طول', 'search'),
('search_max_results', '50', 'حداکثر نتایج', 'search'),
('search_enable_fuzzy', 'true', 'جستجوی مبهم', 'search'),
('search_fuzzy_threshold', '0.6', 'آستانه مبهم', 'search'),
('search_enable_synonyms', 'true', 'مترادف‌ها', 'search'),
('search_synonyms_list', '{}', 'لیست مترادف‌ها', 'search'),
('search_enable_stopwords', 'true', 'کلمات توقف', 'search'),
('search_stopwords_list', '[]', 'لیست کلمات توقف', 'search'),
('search_enable_stemming', 'true', 'ریشه‌یابی', 'search'),
('search_language', '"fa"', 'زبان', 'search'),
('search_enable_highlighting', 'true', 'برجسته‌سازی', 'search'),
('search_enable_suggestions', 'true', 'پیشنهادات', 'search'),
('search_suggestions_limit', '5', 'محدودیت پیشنهادات', 'search'),

-- Mobile Settings (15)
('mobile_enable_responsive', 'true', 'واکنش‌گرا', 'mobile'),
('mobile_enable_pwa', 'false', 'PWA', 'mobile'),
('mobile_pwa_name', '"سیستم هوشمند"', 'نام PWA', 'mobile'),
('mobile_pwa_short_name', '"سیستم"', 'نام کوتاه', 'mobile'),
('mobile_enable_notifications', 'false', 'اعلان‌ها', 'mobile'),
('mobile_enable_offline', 'false', 'حالت آفلاین', 'mobile'),
('mobile_offline_pages', '[]', 'صفحات آفلاین', 'mobile'),
('mobile_enable_gestures', 'true', 'حرکات', 'mobile'),
('mobile_swipe_threshold', '50', 'آستانه سوایپ', 'mobile'),
('mobile_enable_haptic', 'true', 'بازخورد لمسی', 'mobile'),
('mobile_enable_app_banner', 'false', 'بنر اپلیکیشن', 'mobile'),
('mobile_app_store_url', '""', 'URL استور', 'mobile'),
('mobile_play_store_url', '""', 'URL پلی استور', 'mobile'),
('mobile_enable_deep_linking', 'false', 'لینک‌دهی عمیق', 'mobile'),
('mobile_deep_link_scheme', '""', 'طرح لینک', 'mobile'),

-- Advanced Settings (25)
('advanced_enable_debug_mode', 'false', 'حالت دیباگ', 'advanced'),
('advanced_log_level', '"info"', 'سطح لاگ', 'advanced'),
('advanced_enable_profiling', 'false', 'پروفایلینگ', 'advanced'),
('advanced_enable_error_reporting', 'true', 'گزارش خطا', 'advanced'),
('advanced_error_reporting_service', '""', 'سرویس گزارش', 'advanced'),
('advanced_enable_feature_flags', 'true', 'پرچم‌های ویژگی', 'advanced'),
('advanced_feature_flags', '{}', 'پرچم‌ها', 'advanced'),
('advanced_enable_ab_testing', 'false', 'تست A/B', 'advanced'),
('advanced_ab_tests', '[]', 'تست‌ها', 'advanced'),
('advanced_enable_beta_features', 'false', 'ویژگی‌های بتا', 'advanced'),
('advanced_beta_users', '[]', 'کاربران بتا', 'advanced'),
('advanced_enable_maintenance_mode', 'false', 'حالت تعمیر', 'advanced'),
('advanced_maintenance_allowed_ips', '[]', 'IP های مجاز', 'advanced'),
('advanced_enable_custom_code', 'false', 'کد سفارشی', 'advanced'),
('advanced_custom_css', '""', 'CSS سفارشی', 'advanced'),
('advanced_custom_js', '""', 'JS سفارشی', 'advanced'),
('advanced_custom_html_head', '""', 'HTML سفارشی head', 'advanced'),
('advanced_custom_html_body', '""', 'HTML سفارشی body', 'advanced'),
('advanced_enable_webhooks', 'true', 'Webhooks', 'advanced'),
('advanced_webhook_endpoints', '[]', 'نقاط پایانی', 'advanced'),
('advanced_enable_cron_jobs', 'true', 'کارهای زمان‌بندی', 'advanced'),
('advanced_cron_jobs', '[]', 'کارها', 'advanced'),
('advanced_enable_queue_workers', 'true', 'کارگران صف', 'advanced'),
('advanced_queue_worker_count', '4', 'تعداد کارگران', 'advanced'),
('advanced_enable_database_replication', 'false', 'تکرار دیتابیس', 'advanced')
ON CONFLICT (key) DO NOTHING;